apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - ns.yaml
  - alertmanager-http-route.yaml
  - grafana-http-route.yaml
  - prometheus-http-route.yaml
  - additional-scrape-configs.yaml
helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    version: 72.6.3
    releaseName: kube-prometheus-stack
    namespace: monitoring
    valuesFile: values.yaml
