prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10G
    additionalScrapeConfigs:
      name: additional-scrape-configs
      key: prometheus-additional.yaml

nodeExporter:
  enabled: true
  jobLabel: job
  service:
    port: 9100
  serviceMonitor:
    enabled: true
    interval: 15s
    scrapeTimeout: 10s
    relabelings:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
