gitea:
  admin:
    existingSecret: gitea-admin-secret
    usernameKey: username
    passwordKey: password
    emailKey: email

  config:
    server:
      DOMAIN: gitea.internal.cluster.local
      ROOT_URL: http://gitea.internal.cluster.local/

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: gitea.internal.cluster.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
