gitea:
  admin:
    existingSecret: gitea-admin-secret
    usernameKey: username
    passwordKey: password
    emailKey: email

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: gitea.internal.cluster.local
      paths:
        - path: /
          pathType: Prefix
