apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: hello-world
  namespace: hello-world
spec:
  parentRefs:
    - name: gateway-external       # ✅ MUST point to external gateway
      namespace: gateway
      sectionName: https           # ✅ Must match your TLS listener name
  hostnames:
    - "hello-world.wiredgateway.com"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: hello-world
          port: 80                 # ✅ Port must match the Service port
