apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-wiredgateway
  namespace: gateway
spec:
  dnsNames:
    - "*.wiredgateway.com"
    - wiredgateway.com
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: cloudflare-cluster-issuer
  secretName: cert-wiredgateway
  usages:
    - digital signature
    - key encipherment

