apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:

  # Gateway resources
  - gateway-class.yaml
  - ns.yaml
  - gw-external.yaml
  - gw-internal.yaml
  - cert-wiredgateway.yaml
  - cloudflare-cluster-issuer.yaml
  - route-hello.yaml

generatorOptions:
  disableNameSuffixHash: true
