apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applications
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/dspinozz/k3s-argocd-starter.git
        revision: HEAD
        directories:
          - path: my-apps/hello-world
          - path: my-apps/gitea
          - path: my-apps/zot
          - path: my-apps/drone
  template:
    metadata:
      name: hello-world
      labels:
        type: application
    spec:
      project: applications
      source:
        repoURL: https://github.com/dspinozz/k3s-argocd-starter.git
        targetRevision: HEAD
        path: my-apps/hello-world
      destination:
        server: https://kubernetes.default.svc
        namespace: hello-world
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
