apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: headlamp
    repo: https://headlamp-k8s.github.io/headlamp/
    releaseName: headlamp
    namespace: headlamp
    version: 0.29.1
    valuesFile: values.yaml

resources:
  - namespace.yaml
