apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crowdsec-k8s-bouncer
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.crowdsec.net
    chart: crowdsec-kubernetes-bouncer
    targetRevision: 0.7.0
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: crowdsec
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
