# kustomization.yaml
resources:
  - namespace.yaml
  - secret.yaml

helmCharts:
  - name: crowdsec-traefik-bouncer
    repo: https://crowdsecurity.github.io/helm-charts
    version: 0.1.4
    releaseName: crowdsec-traefik-bouncer
    namespace: crowdsec-traefik-bouncer
    valuesFile: values.yaml
