zot:
  http:
    port: 5000
  config:
    storage:
      rootDirectory: /var/lib/zot
    http:
      address: 0.0.0.0
      port: 5000
      accessControl:
        realms:
          - name: public
            resources:
              - method: GET
                regex: .*
