apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

helmCharts:
  - name: minio
    repo: https://charts.bitnami.com/bitnami
    releaseName: minio
    namespace: minio
    version: 12.10.6
    valuesFile: values.yaml
