apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: velero
    repo: https://vmware-tanzu.github.io/helm-charts
    version: 10.0.1
    releaseName: velero
    namespace: velero
    valuesFile: values.yaml

resources:
  - namespace.yaml
  - secret.yaml
