tunnel: k3s-cluster
credentials-file: /etc/cloudflared/credentials/credentials.json
metrics: 0.0.0.0:2000
no-autoupdate: true
loglevel: debug
transport-loglevel: debug
protocol: http2


ingress:
  # Example for a specific service (hello-world)
  - hostname: hello.wiredgateway.com
    service: http://hello-world.hello-world.svc.cluster.local:5678
    originRequest:
      logHeaders: true
      headers:
        - name: CF-Connecting-IP
        - name: X-Real-IP
        - name: CF-IPCountry
        - name: CF-Ray
        - name: CF-Visitor
        - name: CF-Device-Type
        - name: CF-IPCITY
        - name: CF-IPCONTINENT
        - name: CF-IPLATITUDE
        - name: CF-IPLONGITUDE
        - name: CF-IPREGION
        - name: X-Forwarded-For
        - name: Accept-Language
        - name: User-Agent

  # Wildcard for all Gateway-exposed services
  - hostname: "*.wiredgateway.com"
    service: https://cilium-gateway-gateway-external.gateway.svc.cluster.local:443
    originRequest:
      noTLSVerify: true
      originServerName: "*.wiredgateway.com"
      logHeaders: true
      headers:
        - name: CF-Connecting-IP
        - name: X-Real-IP
        - name: CF-IPCountry
        - name: CF-Ray
        - name: CF-Visitor
        - name: CF-Device-Type
        - name: CF-IPCITY
        - name: CF-IPCONTINENT
        - name: CF-IPLATITUDE
        - name: CF-IPLONGITUDE
        - name: CF-IPREGION
        - name: X-Forwarded-For
        - name: Accept-Language
        - name: User-Agent
        - name: True-Client-IP
        - name: CF-Client-Bot
        - name: CF-Bot-Score
        - name: CF-Bot-Management-Tag
        - name: CF-Worker
        - name: CF-Challenge

  # Root domain
  - hostname: wiredgateway.com
    service: https://cilium-gateway-gateway-external.gateway.svc.cluster.local:443
    originRequest:
      noTLSVerify: true
      originServerName: wiredgateway.com
      logHeaders: true
      headers:
        - name: CF-Connecting-IP
        - name: X-Real-IP
        - name: CF-IPCountry
        - name: CF-Ray
        - name: CF-Visitor
        - name: CF-Device-Type
        - name: CF-IPCITY
        - name: CF-IPCONTINENT
        - name: CF-IPLATITUDE
        - name: CF-IPLONGITUDE
        - name: CF-IPREGION
        - name: X-Forwarded-For
        - name: Accept-Language
        - name: User-Agent

  # Default fallback
  - service: http_status:404
