apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tetragon

helmCharts:
  - name: tetragon
    repo: https://cilium.github.io/charts
    version: 1.0.0
    releaseName: tetragon
    namespace: tetragon
    valuesFile: values.yaml

resources:
  - namespace.yaml
