tetragon:
  enabled: true

# Enable the Tetragon operator
operator:
  enabled: true

# Configure Tetragon log output path
tetragonConfig:
  exportFilename: /var/run/cilium/tetragon/tetragon.log
  # Use hostPath to persist logs to node filesystem for Wazuh agent access
  logMountPath: /var/run/cilium/tetragon
  logHostPath: /var/run/cilium/tetragon

# Recommended defaults (can tune later)
enableK8sAPIAccount: true
enableProcessCred: true
enableProcessNs: true
enableProcessExec: true
enableProcessExit: true
enableProcessTTY: true
enableProcessKprobe: true
