tetragon:
  enabled: true

  # Enable the Tetragon operator
  operator:
    enabled: true

  # Configure Tetragon log output path
  tetragonConfig:
    logPath: /var/log/tetragon/tetragon.log

  # Use hostPath to persist logs to node filesystem for Wazuh agent access
  logMountPath: /var/log/tetragon
  logHostPath: /var/log/tetragon

  # Recommended defaults (can tune later)
  enableK8sAPIAccess: true
  enableProcessCred: true
  enableProcessNs: true
  enableProcessExec: true
  enableProcessExit: true
  enableProcessTTY: true
  enableProcessKprobe: true
